# Generated by Django 5.1.4 on 2025-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vn_rule_name', models.CharField(max_length=255)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_description', models.TextField()),
                ('example', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
